#![allow(non_snake_case)]
// Generated by `cargo nirvash materialize-tests`
// Cargo discovers this integration test crate and includes files from tests/generated/*.rs.

#[path = "generated/src_model_rs__line126_col0_LockManagerSpec_e2e_default_replay.rs"]
mod src_model_rs__line126_col0_LockManagerSpec_e2e_default_replay;
